# Generated by Django 3.0.8 on 2020-07-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='petal_width',
            field=models.FloatField(default=0.0),
        ),
    ]
